In [2]:
l = [23245, 27, 546, 215]

In [3]:
l

[23245, 27, 546, 215]

In [4]:
l[1:] #for list, you're creating a copy while slicing

[27, 546, 215]

In [5]:
l[0:2]

[23245, 27]

In [6]:
l[::2]

[23245, 546]

In [7]:
import numpy as np

In [8]:
a = np.array(l)

In [9]:
a

array([23245,    27,   546,   215])

In [10]:
a[2:] #for array, you're not creating a copy of the array while slicing. You're creating a view of the array. 

array([546, 215])

In [11]:
a[2:4]

array([546, 215])

In [12]:
b = a[2:4]

In [13]:
b

array([546, 215])

In [14]:
b[0]

546

In [15]:
b[:]

array([546, 215])

In [16]:
b[:]=111

In [17]:
b

array([111, 111])

In [18]:
a  #if we change b, a will change too. numpy wants to save space and doesn't want to use computer's resources by accident. 

array([23245,    27,   111,   111])

In [19]:
c = a.copy() #in order to create a copy of an array, need to call the copy function

In [20]:
c[0]=0

In [21]:
c

array([  0,  27, 111, 111])

In [22]:
a

array([23245,    27,   111,   111])

In [23]:
len(a)

4

In [25]:
min(a)

27

In [26]:
a.mean()

5873.5